import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-gray-100`}>
        <TRPCReactProvider>
          <div className="min-h-screen flex flex-col px-2 py-2 gap-y-1">
            {/* Main content grows to push footer down */}
            <main className="flex-1">{children}</main>

            {/* Sticky footer at bottom */}
            <Footer />
          </div>

          <Toaster position="top-center" />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
